services:
  geo-postgis:
    image: postgis/postgis:15-3.3
    container_name: geo-postgis
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - geo_postgis_data:/var/lib/postgresql/data
    networks:
      - geo-geodata-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  geo-geodata-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geo-geodata-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://geo-postgis:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "${GEODATA_SERVICE_PORT}:8080"
    depends_on:
      geo-postgis:
        condition: service_healthy
    networks:
      - geo-geodata-net

networks:
  geo-geodata-net:
    name: geo-geodata-net
    driver: bridge

volumes:
  geo_postgis_data: